#!/bin/bash

readonly program="$(basename "${0}")"
readonly scripts_dir='/Library/LowChimeHelpers'
readonly save_settings_script='/Library/LowChimeHelpers/save_settings.bash'
readonly restore_settings_script='/Library/LowChimeHelpers/restore_settings.bash'

function usage {
  echo "
    Lower the volume of macOS’s startup chime

    Usage:
      sudo ${program} <install|uninstall>

    Options:
      -h, --help   Show this help.
  " | sed -E 's/^ {4}//'
}

if [[ "${1}" =~ ^(-h|--help)$ ]]; then
  usage
  exit 0
fi

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Needs to be called with administrative privileges (sudo)." >&2
  exit 1
fi

if [[ "${1}" == 'uninstall' ]]; then
  rm -r "${scripts_dir}"
  defaults delete com.apple.loginwindow LoginHook
  defaults delete com.apple.loginwindow LogoutHook

  echo 'Script uninstall complete. For a complete removal, you may delete the ~/.config/lowchime file for each user, though leaving it does no harm.'
  exit 0
elif [[ "${1}" == 'install' ]]; then
  mkdir -p "${scripts_dir}"

  echo '#!/bin/bash

    readonly settings_dir="/Users/${1}/.config" # In login/logout scripts, ${1} returns the short name of the user who is logging in
    readonly settings_file="${settings_dir}/lowchime"
    readonly desired_chime_volume="10"
    readonly current_volume="$(osascript -e "output volume of (get volume settings)")"
    readonly current_mute="$(osascript -e "get output muted of (get volume settings)")"

    mkdir -p "${settings_dir}"

    readonly volume_state="output volume ${current_volume}"

    readonly mute_state="$(
      if [[ "${current_mute}" == "false" ]]; then
        echo -n "without output muted"
      else
        echo -n "with output muted"
      fi
    )"

    echo "${volume_state} ${mute_state}" > "${settings_file}"
    osascript -e "set volume output volume ${desired_chime_volume} without output muted"
  ' | sed -E 's/^ {4}//' > "${save_settings_script}"

  echo '#!/bin/bash

    readonly settings_dir="/Users/${1}/.config" # In login/logout scripts, ${1} returns the short name of the user who is logging in
    readonly settings_file="${settings_dir}/lowchime"

    [[ -f "${settings_file}" ]] && osascript -e "set volume $(< "${settings_file}")"
  ' | sed -E 's/^ {4}//' > "${restore_settings_script}"

  chmod +x "${save_settings_script}" "${restore_settings_script}"
  defaults write com.apple.loginwindow LoginHook "${restore_settings_script}"
  defaults write com.apple.loginwindow LogoutHook "${save_settings_script}"

  echo 'Scripts installed successfully.'
  exit 0
else
  usage
  exit 1
fi
